// <auto-generated />
using DocFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocFlow.Infrastructure.Migrations
{
    [DbContext(typeof(DocFlowDbContext))]
    [Migration("20250729135130_DocumentDataType")]
    partial class DocumentDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("df")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocFlow.Domain.Entities.Formular", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DocumentData")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.HasKey("Id");

                    b.ToTable("Formulars", "df");
                });

            modelBuilder.Entity("DocFlow.Domain.Entities.Formular", b =>
                {
                    b.OwnsOne("DocFlow.Domain.Values.Presentable", "Presentable", b1 =>
                        {
                            b1.Property<int>("FormularId")
                                .HasColumnType("int");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.Property<int>("SequenceNumber")
                                .HasColumnType("int");

                            b1.HasKey("FormularId");

                            b1.ToTable("Formulars", "df");

                            b1.WithOwner()
                                .HasForeignKey("FormularId");
                        });

                    b.Navigation("Presentable")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
